[package]
name = "client"
version = "0.1.0"
authors = ["obviyus"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
ureq = { version = "*", features = ["json", "charset"] }